services:
  core_server:
    build:
      context: .
      dockerfile: CoreDockerfile
    env_file: /home/naro/data_analyst_llm/data_analyst_llm/app/env/extra.env
    environment:
    - HOST_CONFIGS_DIR=/home/naro/data_analyst_llm/data_analyst_llm/app/configs
    - HOST_ENV_DIR=/home/naro/data_analyst_llm/data_analyst_llm/app/env
    image: core-server
    ports:
    - 8000:8000
    volumes:
    - /home/naro/data_analyst_llm/data_analyst_llm/app/configs:/app/configs
    - /home/naro/data_analyst_llm/data_analyst_llm/app/env:/app/env
    - /var/run/docker.sock:/var/run/docker.sock
version: '3.8'
